import type {
  ClienteParticular,
  DashboardData,
  Despesa,
  Endereco,
  Equipe,
  LojaParceira,
  Montador,
  OrdemServico,
  Produto,
  Salario,
} from './types'

function endereco(data: Endereco): Endereco {
  return data
}

export const mockMontadores: Montador[] = [
  {
    id: '1',
    nome: 'Carlos Silva',
    email: 'carlos@montagex.com.br',
    telefone: '(11) 99999-1001',
    tipo: 'montador',
    ativo: true,
    percentualSalario: 30,
    chavePix: 'carlos@pix.com',
    metaMensal: 9000,
    criadoEm: new Date('2025-05-12T09:00:00'),
  },
  {
    id: '2',
    nome: 'Roberto Santos',
    email: 'roberto@montagex.com.br',
    telefone: '(11) 99999-1002',
    tipo: 'montador',
    ativo: true,
    percentualSalario: 28,
    chavePix: '11999991002',
    metaMensal: 8000,
    criadoEm: new Date('2025-06-02T09:00:00'),
  },
  {
    id: '3',
    nome: 'Fernando Lima',
    email: 'fernando@montagex.com.br',
    telefone: '(11) 99999-1003',
    tipo: 'montador',
    ativo: true,
    percentualSalario: 27,
    chavePix: 'fernando@pix.com',
    metaMensal: 7000,
    criadoEm: new Date('2025-07-10T09:00:00'),
  },
  {
    id: '4',
    nome: 'Diego Costa',
    email: 'diego@montagex.com.br',
    telefone: '(11) 99999-1004',
    tipo: 'montador',
    ativo: true,
    percentualSalario: 25,
    chavePix: '11999991004',
    metaMensal: 6000,
    criadoEm: new Date('2025-08-15T09:00:00'),
  },
  {
    id: '5',
    nome: 'Joao Nunes',
    email: 'joao@montagex.com.br',
    telefone: '(11) 99999-1005',
    tipo: 'montador',
    ativo: false,
    percentualSalario: 24,
    metaMensal: 5500,
    criadoEm: new Date('2025-09-05T09:00:00'),
  },
]

export const mockEquipes: Equipe[] = [
  {
    id: 'eq-1',
    nome: 'Equipe Alpha',
    membros: [mockMontadores[0], mockMontadores[1]],
    lider: mockMontadores[0],
    ativa: true,
  },
  {
    id: 'eq-2',
    nome: 'Equipe Beta',
    membros: [mockMontadores[2], mockMontadores[3]],
    lider: mockMontadores[2],
    ativa: true,
  },
  {
    id: 'eq-3',
    nome: 'Equipe Suporte',
    membros: [mockMontadores[4]],
    lider: mockMontadores[4],
    ativa: false,
  },
]

export const mockLojas: LojaParceira[] = [
  {
    id: 'loja-1',
    razaoSocial: 'Casa e Conforto Moveis Ltda',
    nomeFantasia: 'Casa e Conforto',
    cnpj: '12.345.678/0001-10',
    endereco: endereco({
      cep: '01310-200',
      logradouro: 'Av. Paulista',
      numero: '1200',
      bairro: 'Bela Vista',
      cidade: 'Sao Paulo',
      estado: 'SP',
    }),
    telefone: '(11) 3333-1000',
    email: 'financeiro@casaeconforto.com.br',
    tipoRepasse: 'percentual',
    valorRepasse: 12,
    ativa: true,
    divida: 2450,
    criadoEm: new Date('2024-11-10T09:00:00'),
  },
  {
    id: 'loja-2',
    razaoSocial: 'Moveis Premium Comercio SA',
    nomeFantasia: 'Moveis Premium',
    cnpj: '98.765.432/0001-55',
    endereco: endereco({
      cep: '04002-020',
      logradouro: 'Rua Vergueiro',
      numero: '530',
      bairro: 'Paraiso',
      cidade: 'Sao Paulo',
      estado: 'SP',
    }),
    telefone: '(11) 3222-2000',
    email: 'contato@moveispremium.com.br',
    tipoRepasse: 'fixo',
    valorRepasse: 180,
    ativa: true,
    divida: 1890,
    criadoEm: new Date('2024-12-01T09:00:00'),
  },
  {
    id: 'loja-3',
    razaoSocial: 'Lar Decorado Interiores Ltda',
    nomeFantasia: 'Lar Decorado',
    cnpj: '23.111.222/0001-88',
    endereco: endereco({
      cep: '09190-340',
      logradouro: 'Av. Industrial',
      numero: '900',
      bairro: 'Jardim',
      cidade: 'Santo Andre',
      estado: 'SP',
    }),
    telefone: '(11) 3666-3000',
    email: 'financeiro@lardecorado.com.br',
    tipoRepasse: 'percentual',
    valorRepasse: 10,
    ativa: true,
    divida: 980,
    criadoEm: new Date('2025-01-20T09:00:00'),
  },
  {
    id: 'loja-4',
    razaoSocial: 'Pratico Home Center Ltda',
    nomeFantasia: 'Pratico Home',
    cnpj: '88.777.666/0001-44',
    endereco: endereco({
      cep: '09750-100',
      logradouro: 'Rua Marechal Deodoro',
      numero: '240',
      bairro: 'Centro',
      cidade: 'Sao Bernardo do Campo',
      estado: 'SP',
    }),
    telefone: '(11) 3555-4000',
    email: 'contato@praticohome.com.br',
    tipoRepasse: 'fixo',
    valorRepasse: 150,
    ativa: false,
    divida: 0,
    criadoEm: new Date('2025-02-10T09:00:00'),
  },
]

export const mockClientesParticulares: ClienteParticular[] = [
  {
    id: 'cli-1',
    nome: 'Mariana Oliveira',
    cpf: '123.456.789-00',
    endereco: endereco({
      cep: '04120-001',
      logradouro: 'Rua Domingos de Morais',
      numero: '100',
      complemento: 'Apto 72',
      bairro: 'Vila Mariana',
      cidade: 'Sao Paulo',
      estado: 'SP',
    }),
    telefone: '(11) 98888-0001',
    email: 'mariana.oliveira@email.com',
    observacoes: 'Preferencia por atendimento no periodo da manha.',
    criadoEm: new Date('2025-10-03T09:00:00'),
  },
  {
    id: 'cli-2',
    nome: 'Felipe Andrade',
    cpf: '987.654.321-00',
    endereco: endereco({
      cep: '09015-240',
      logradouro: 'Rua das Figueiras',
      numero: '345',
      bairro: 'Jardim',
      cidade: 'Santo Andre',
      estado: 'SP',
    }),
    telefone: '(11) 97777-0002',
    email: 'felipe.andrade@email.com',
    criadoEm: new Date('2025-10-22T09:00:00'),
  },
  {
    id: 'cli-3',
    nome: 'Aline Barbosa',
    cpf: '321.123.456-09',
    endereco: endereco({
      cep: '09810-300',
      logradouro: 'Av. Kennedy',
      numero: '2200',
      bairro: 'Anchieta',
      cidade: 'Sao Bernardo do Campo',
      estado: 'SP',
    }),
    telefone: '(11) 96666-0003',
    observacoes: 'Condominio exige cadastro previo dos montadores.',
    criadoEm: new Date('2025-11-05T09:00:00'),
  },
  {
    id: 'cli-4',
    nome: 'Rafaela Gomes',
    cpf: '555.444.333-22',
    endereco: endereco({
      cep: '11060-002',
      logradouro: 'Rua Guaia',
      numero: '45',
      bairro: 'Embare',
      cidade: 'Santos',
      estado: 'SP',
    }),
    telefone: '(13) 95555-0004',
    email: 'rafaela.gomes@email.com',
    criadoEm: new Date('2025-12-15T09:00:00'),
  },
  {
    id: 'cli-5',
    nome: 'Tiago Mendes',
    cpf: '111.222.333-44',
    endereco: endereco({
      cep: '09940-300',
      logradouro: 'Rua das Acacias',
      numero: '98',
      bairro: 'Centro',
      cidade: 'Diadema',
      estado: 'SP',
    }),
    telefone: '(11) 94444-0005',
    criadoEm: new Date('2026-01-11T09:00:00'),
  },
]

export const mockProdutos: Produto[] = [
  {
    id: 'prod-1',
    codigo: 'GRD-001',
    nome: 'Guarda-roupa 6 portas',
    descricao: 'Modelo casal com duas gavetas internas.',
    categoria: 'Guarda-roupa',
    tempoBase: 120,
    tempoEstimado: 180,
    valorBase: 350,
    valorMontagem: 420,
    lojaId: 'loja-1',
    ativo: true,
  },
  {
    id: 'prod-2',
    codigo: 'COZ-010',
    nome: 'Armario de cozinha 8 portas',
    descricao: 'Modulo completo de parede e piso.',
    categoria: 'Cozinha',
    tempoBase: 160,
    tempoEstimado: 240,
    valorBase: 420,
    valorMontagem: 520,
    lojaId: 'loja-2',
    ativo: true,
  },
  {
    id: 'prod-3',
    codigo: 'SLA-021',
    nome: 'Painel de TV 65',
    descricao: 'Painel com nicho e suporte para passagem de cabos.',
    categoria: 'Sala',
    tempoBase: 70,
    tempoEstimado: 100,
    valorBase: 180,
    valorMontagem: 240,
    lojaId: 'loja-3',
    ativo: true,
  },
  {
    id: 'prod-4',
    codigo: 'QRT-009',
    nome: 'Cama box bau queen',
    descricao: 'Com cabaceira estofada e montagem de ferragens.',
    categoria: 'Quarto',
    tempoBase: 90,
    tempoEstimado: 130,
    valorBase: 220,
    valorMontagem: 290,
    lojaId: 'loja-1',
    ativo: true,
  },
  {
    id: 'prod-5',
    codigo: 'ESC-005',
    nome: 'Mesa de escritorio em L',
    descricao: 'Tampo duplo com gaveteiro lateral.',
    categoria: 'Escritório',
    tempoBase: 80,
    tempoEstimado: 115,
    valorBase: 170,
    valorMontagem: 210,
    lojaId: 'loja-4',
    ativo: false,
  },
]

export const mockOrdensServico: OrdemServico[] = [
  {
    id: 'os-1001',
    numero: 'OS-2026-001',
    clienteId: 'loja-1',
    tipoCliente: 'loja',
    enderecoEntrega: endereco({
      cep: '04110-010',
      logradouro: 'Rua Afonso Celso',
      numero: '1400',
      bairro: 'Vila Mariana',
      cidade: 'Sao Paulo',
      estado: 'SP',
    }),
    dataAgendada: new Date('2026-03-19T09:00:00'),
    janelaHorario: { inicio: '09:00', fim: '12:00' },
    produtos: [
      {
        id: 'item-1',
        produtoId: 'prod-1',
        quantidade: 1,
        valorUnitario: 350,
        valorTotal: 350,
      },
    ],
    montadores: [mockMontadores[0], mockMontadores[1]],
    equipeId: 'eq-1',
    status: 'agendada',
    prioridade: 'normal',
    valorTotal: 420,
    valorMontagem: 420,
    observacoes: 'Cliente solicitou contato 30 minutos antes.',
    fotos: [],
    criadoEm: new Date('2026-03-17T10:00:00'),
    atualizadoEm: new Date('2026-03-17T10:00:00'),
  },
  {
    id: 'os-1002',
    numero: 'OS-2026-002',
    clienteId: 'cli-1',
    tipoCliente: 'particular',
    enderecoEntrega: mockClientesParticulares[0].endereco,
    dataAgendada: new Date('2026-03-18T14:00:00'),
    janelaHorario: { inicio: '14:00', fim: '17:00' },
    produtos: [
      {
        id: 'item-2',
        produtoId: 'prod-2',
        quantidade: 1,
        valorUnitario: 420,
        valorTotal: 420,
      },
      {
        id: 'item-3',
        produtoId: 'prod-3',
        quantidade: 1,
        valorUnitario: 180,
        valorTotal: 180,
      },
    ],
    montadores: [mockMontadores[2], mockMontadores[3]],
    equipeId: 'eq-2',
    status: 'em_andamento',
    prioridade: 'alta',
    valorTotal: 760,
    valorMontagem: 760,
    fotos: [],
    checkInAt: new Date('2026-03-18T14:12:00'),
    criadoEm: new Date('2026-03-16T15:00:00'),
    atualizadoEm: new Date('2026-03-18T14:12:00'),
  },
  {
    id: 'os-1003',
    numero: 'OS-2026-003',
    clienteId: 'cli-2',
    tipoCliente: 'particular',
    enderecoEntrega: mockClientesParticulares[1].endereco,
    dataAgendada: new Date('2026-03-16T08:00:00'),
    janelaHorario: { inicio: '08:00', fim: '11:00' },
    produtos: [
      {
        id: 'item-4',
        produtoId: 'prod-4',
        quantidade: 1,
        valorUnitario: 220,
        valorTotal: 220,
      },
    ],
    montadores: [mockMontadores[1]],
    equipeId: 'eq-1',
    status: 'concluida',
    prioridade: 'normal',
    valorTotal: 290,
    valorMontagem: 290,
    fotos: [],
    checkInAt: new Date('2026-03-16T08:05:00'),
    checkOutAt: new Date('2026-03-16T10:45:00'),
    criadoEm: new Date('2026-03-14T11:00:00'),
    atualizadoEm: new Date('2026-03-16T10:45:00'),
  },
  {
    id: 'os-1004',
    numero: 'OS-2026-004',
    clienteId: 'loja-2',
    tipoCliente: 'loja',
    enderecoEntrega: endereco({
      cep: '04543-000',
      logradouro: 'Rua Funchal',
      numero: '450',
      bairro: 'Vila Olimpia',
      cidade: 'Sao Paulo',
      estado: 'SP',
    }),
    dataAgendada: new Date('2026-03-20T13:00:00'),
    janelaHorario: { inicio: '13:00', fim: '16:00' },
    produtos: [
      {
        id: 'item-5',
        produtoId: 'prod-3',
        quantidade: 2,
        valorUnitario: 180,
        valorTotal: 360,
      },
    ],
    montadores: [mockMontadores[0], mockMontadores[2]],
    equipeId: 'eq-1',
    status: 'pendente',
    prioridade: 'urgente',
    valorTotal: 480,
    valorMontagem: 480,
    observacoes: 'Aguardando confirmacao do cliente final.',
    fotos: [],
    criadoEm: new Date('2026-03-18T09:00:00'),
    atualizadoEm: new Date('2026-03-18T09:00:00'),
  },
]

export const mockDespesas: Despesa[] = [
  {
    id: 'desp-1',
    descricao: 'Combustivel - rota zona sul',
    categoria: 'combustivel',
    valor: 420,
    data: new Date('2026-03-02T10:00:00'),
    observacoes: 'Abastecimento de dois veiculos',
  },
  {
    id: 'desp-2',
    descricao: 'Compra de parafusadeira',
    categoria: 'ferramentas',
    valor: 890,
    data: new Date('2026-03-05T10:00:00'),
  },
  {
    id: 'desp-3',
    descricao: 'Materiais de embalagem',
    categoria: 'material',
    valor: 320,
    data: new Date('2026-03-08T10:00:00'),
  },
  {
    id: 'desp-4',
    descricao: 'Manutencao da van',
    categoria: 'veiculo',
    valor: 760,
    data: new Date('2026-03-12T10:00:00'),
    observacoes: 'Troca de oleo e pastilhas',
  },
  {
    id: 'desp-5',
    descricao: 'Despesas administrativas',
    categoria: 'outros',
    valor: 180,
    data: new Date('2026-03-15T10:00:00'),
  },
]

export const mockSalarios: Salario[] = [
  {
    id: 'sal-1',
    montadorId: '1',
    montador: mockMontadores[0],
    mes: 3,
    ano: 2026,
    valorBruto: 9200,
    valorLiquido: 8500,
    descontos: 700,
    bonus: 400,
    status: 'pago',
    dataPagamento: new Date('2026-03-10T10:00:00'),
  },
  {
    id: 'sal-2',
    montadorId: '2',
    montador: mockMontadores[1],
    mes: 3,
    ano: 2026,
    valorBruto: 6800,
    valorLiquido: 6200,
    descontos: 600,
    bonus: 200,
    status: 'pago',
    dataPagamento: new Date('2026-03-10T10:00:00'),
  },
  {
    id: 'sal-3',
    montadorId: '3',
    montador: mockMontadores[2],
    mes: 3,
    ano: 2026,
    valorBruto: 5600,
    valorLiquido: 5100,
    descontos: 500,
    bonus: 150,
    status: 'pendente',
  },
  {
    id: 'sal-4',
    montadorId: '4',
    montador: mockMontadores[3],
    mes: 3,
    ano: 2026,
    valorBruto: 4100,
    valorLiquido: 3800,
    descontos: 300,
    bonus: 80,
    status: 'pendente',
  },
]

export const mockDashboardData: DashboardData = {
  financeiro: {
    receitaTotal: 158000,
    receitaLojas: 112000,
    receitaParticulares: 46000,
    despesasTotal: 48200,
    lucroLiquido: 109800,
    pendentes: 12400,
  },
  operacional: {
    servicosAgendados: mockOrdensServico.filter((os) => os.status === 'agendada').length,
    servicosEmAndamento: mockOrdensServico.filter((os) => os.status === 'em_andamento').length,
    servicosConcluidos: mockOrdensServico.filter((os) => os.status === 'concluida').length,
    servicosCancelados: mockOrdensServico.filter((os) => os.status === 'cancelada').length,
    montadoresAtivos: mockMontadores.filter((m) => m.ativo).length,
    equipesAtivas: mockEquipes.filter((e) => e.ativa).length,
    clientesAtivos: mockClientesParticulares.length,
    lojasAtivas: mockLojas.filter((l) => l.ativa).length,
  },
  graficos: {
    receitasPorTipo: [
      { tipo: 'Lojas', valor: 112000 },
      { tipo: 'Particulares', valor: 46000 },
    ],
    despesasPorCategoria: [
      { categoria: 'Combustivel', valor: 12800 },
      { categoria: 'Ferramentas', valor: 9800 },
      { categoria: 'Material', valor: 7400 },
      { categoria: 'Veiculo', valor: 12600 },
      { categoria: 'Outros', valor: 5600 },
    ],
    servicosPorStatus: [
      { status: 'Agendada', quantidade: 9 },
      { status: 'Em andamento', quantidade: 4 },
      { status: 'Concluida', quantidade: 21 },
      { status: 'Cancelada', quantidade: 2 },
    ],
    receitaMensal: [
      { mes: 'Out', receita: 98000, despesa: 42000 },
      { mes: 'Nov', receita: 104000, despesa: 43000 },
      { mes: 'Dez', receita: 116000, despesa: 45000 },
      { mes: 'Jan', receita: 128000, despesa: 46800 },
      { mes: 'Fev', receita: 141000, despesa: 47000 },
      { mes: 'Mar', receita: 158000, despesa: 48200 },
    ],
  },
}
